project: 
  type: book

book: 
  page-navigation: true
  title: "SignalFlowEEG Book" 
  site-url: "https://cincibrainlab.github.io/signalfloweegbook/" 
  repo-url: "https://github.com/cincibrainlab/signalfloweegbook"
  repo-actions: [edit, source, issue]
  favicon: assets/favicon.ico
  downloads: [pdf, docx]
  search: true
  author:
    - name: Ernie Pedapati
      affiliations:
        - name: Cincinnati Children's Hospital Medical Center
          department: Neurobehavioral Research Laboratory
  chapters:
    - index.qmd
    - part: "CORTICAL EXCITABILITY"
      chapters:
        - content/p010_project_overview.qmd
        - content/p050_setup_environment.qmd
        - content/p100_load_catalog.qmd
        #- content/p200_preprocess_data.qmd
        - content/setup_docker.qmd
    - part: "MANUSCRIPT REPOSITORY"
      chapters:
        - content/p200_manuscript_repository.qmd
    - part: "ODDS AND ENDS"
      chapters:
        - content/odds_and_ends.qmd


  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/sflogo.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://cincibrainlab.github.io/
        text: "CinciBrain Lab"
    style: "docked"
    search: true
    collapse-level: 1

bibliography: [content/references.bib]

execute:
  echo: false
  code-overflow: wrap

format:
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    keep-tex: true
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss] 
    toc: true
    toc-depth: 3

filters:
  - assets/include-files.lua
  - quarto

# Comment next 2 lines if the PDF is having trouble
metadata-files:
  - _frontmatter.yml
 
